### PR TITLE
making it easier to override defaults in login screen

### PR DESCRIPTION
**Pull request by missjwo**

### CODE REVIEW

**Comment by missjwo** [comment]
Hey @mattheu  when you can, can you  also make a release version so AWOR pulls in the latest stuff. Cheers

**Comment by mattheu** [comment]
I've updated the version of the theme used by Human Made Website if that's what you mean?

**Comment by missjwo** [comment]
@mattheu i thought you did a release tag of the hm-handbook, so that  when using the submodule it would pull the release tag?

**Comment by mattheu** [comment]
@missjwo I've not done any tags/releases for the handbook. But its fine to just check out the submodule to the latest master. I have done tagged releases for the pattern library, but again also its fine to just track `gh-pages` branch as this is just the same as 'latest release branch' - so I think we're all good here!

**Comment by missjwo** [comment]
@mattheu  Gotcha! my mistake Thanks :)

**Pull request merged**
